#!/bin/bash

# Database Setup Script for Supabase
# هذا السكريبت يساعدك في تطبيق الـ migrations على قاعدة بيانات Supabase

echo "================================================"
echo "  Supabase Database Setup"
echo "  إعداد قاعدة بيانات Supabase"
echo "================================================"
echo ""

PROJECT_ID="vpsdajedntuzftvvjepe"
SUPABASE_URL="https://vpsdajedntuzftvvjepe.supabase.co"

echo "Project ID: $PROJECT_ID"
echo "Supabase URL: $SUPABASE_URL"
echo ""

echo "لتطبيق الـ migrations، لديك خياران:"
echo "To apply migrations, you have two options:"
echo ""

echo "الخيار 1: استخدام Supabase Dashboard (موصى به)"
echo "Option 1: Using Supabase Dashboard (Recommended)"
echo "-------------------------------------------"
echo "1. افتح: https://app.supabase.com/project/$PROJECT_ID/sql/new"
echo "   Open: https://app.supabase.com/project/$PROJECT_ID/sql/new"
echo ""
echo "2. انسخ محتوى الملفات التالية بالترتيب:"
echo "   Copy the content of the following files in order:"
echo ""
echo "   أ) supabase/migrations/20260215_create_authentication_system.sql"
echo "   b) supabase/migrations/20260215_create_rls_policies.sql"
echo "   c) supabase/migrations/20260215_insert_sample_data.sql (اختياري/optional)"
echo ""
echo "3. الصق المحتوى في SQL Editor ونفذه"
echo "   Paste the content in SQL Editor and execute"
echo ""

echo "الخيار 2: استخدام Supabase CLI"
echo "Option 2: Using Supabase CLI"
echo "-------------------------------------------"
echo "1. تثبيت Supabase CLI:"
echo "   Install Supabase CLI:"
echo "   npm install -g supabase"
echo ""
echo "2. تسجيل الدخول:"
echo "   Login:"
echo "   supabase login"
echo ""
echo "3. ربط المشروع:"
echo "   Link project:"
echo "   supabase link --project-ref $PROJECT_ID"
echo ""
echo "4. تطبيق الـ migrations:"
echo "   Apply migrations:"
echo "   supabase db push"
echo ""

echo "================================================"
echo "بعد تطبيق الـ migrations، يمكنك:"
echo "After applying migrations, you can:"
echo "================================================"
echo ""
echo "1. تسجيل الدخول بحسابات تجريبية:"
echo "   Login with test accounts:"
echo "   - dr.ahmed@example.com (Doctor)"
echo "   - info@cairo.hospital.com (Hospital)"
echo "   - volunteer1@example.com (Volunteer)"
echo "   - info@elshifa.pharmacy.com (Pharmacy)"
echo "   - info@alpha.lab.com (Lab)"
echo "   Password for all: password123"
echo ""
echo "2. إنشاء حسابات جديدة من خلال التطبيق"
echo "   Create new accounts through the application"
echo ""

echo "================================================"
echo "ملاحظات مهمة | Important Notes"
echo "================================================"
echo "- كلمات المرور في البيانات التجريبية مشفرة بـ SHA-256"
echo "  Passwords in sample data are hashed with SHA-256"
echo ""
echo "- في الإنتاج، استخدم bcrypt أو argon2"
echo "  In production, use bcrypt or argon2"
echo ""
echo "- جميع الجداول محمية بـ Row Level Security"
echo "  All tables are protected with Row Level Security"
echo ""
echo "- المستخدمون العاديون لا يحتاجون لتسجيل دخول"
echo "  Regular users don't need to login"
echo ""

echo "================================================"
echo "للمساعدة | For Help"
echo "================================================"
echo "راجع ملف: supabase/DATABASE_README.md"
echo "Check file: supabase/DATABASE_README.md"
echo ""
